name: Ventanilla Unica Deploy

on:
  workflow_run:
    workflows: ["Ventanilla Unica Tests"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    # Configura la llave SSH
    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
    # Ejecuta los pasos de despliegue
    - name: Pull latest code and deploy
      run: |
        set -e
        ssh root@${{ secrets.SERVER_IP }} << 'EOF'
          set -e
          
          # Define rollback function
          rollback() {
            echo "Error detected, rolling back..."
            git reset --hard HEAD@{1}  # Revert to previous commit
          }
          trap rollback ERR  # Execute rollback if an error occurs

          cd ventanilla-unica/
          git reset --hard
          git pull origin master

          cd ventanilla-unica-api/
          docker-compose run --rm composer install --no-dev --optimize-autoloader
          docker-compose run --rm artisan migrate --force  # If this fails, rollback will trigger
          docker-compose run --rm  artisan config:cache
          docker-compose run --rm  artisan route:cache
          docker-compose run --rm  artisan view:cache
          chmod -R 775 storage bootstrap/cache
          chown -R www-data:www-data storage bootstrap/cache
        EOF
